### ISSUE TITLE
Clone shared_configs

### ISSUE THREAD

**Issue by dazza-codes** [sul-dlss/capistrano-shared_configs#4]
At present, these tasks depend on puppet to get the shared_configs branch onto the server.  Can we clone the shared_configs repo and checkout the correct branch, using a default branch name or an arg to specify the branch name to checkout?

**Comment by jkeck** [comment]
I think there is more setup that needs to be done by puppet for this whole thing to work, so I'm not sure that's the concern of this codebase itself.

**Comment by dazza-codes** [comment]
Sometimes there are problems with puppet assumptions about one-app per machine and it’s difficult to get it setup to clone more than one shared_configs repo to the system; so this could be an option to work around that.
